# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Filmoteca_Reservas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from PyQt5.QtCore import QStringListModel
from PyQt5.QtWidgets import (QWidget, QPushButton, QLineEdit, QInputDialog, QApplication, QLabel)
import sys
import numpy as np
import matplotlib.pyplot as plt; plt.rcdefaults()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1500, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 1155, 549))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutTitle = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutTitle.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutTitle.setObjectName("gridLayoutTitle")
        self.gridLayoutContent = QtWidgets.QGridLayout()
        self.gridLayoutContent.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayoutContent.setObjectName("gridLayoutContent")
        self.frameConsultarFilmes = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frameConsultarFilmes.setFrameShape(QtWidgets.QFrame.Box)
        self.frameConsultarFilmes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameConsultarFilmes.setLineWidth(2)
        self.frameConsultarFilmes.setObjectName("frameConsultarFilmes")
        self.gridLayout = QtWidgets.QGridLayout(self.frameConsultarFilmes)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonGrafico = QtWidgets.QPushButton(self.frameConsultarFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonGrafico.setFont(font)
        self.pushButtonGrafico.setObjectName("pushButtonGrafico")
        self.gridLayout.addWidget(self.pushButtonGrafico, 1, 2, 1, 1)
        self.pushButtonAtualizarTabela = QtWidgets.QPushButton(self.frameConsultarFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonAtualizarTabela.setFont(font)
        self.pushButtonAtualizarTabela.setObjectName("pushButtonAtualizarTabela")
        self.gridLayout.addWidget(self.pushButtonAtualizarTabela, 1, 1, 1, 1)
        self.tableWidgetFilmes = QtWidgets.QTableWidget(self.frameConsultarFilmes)
        self.tableWidgetFilmes.setObjectName("tableWidgetFilmes")
        self.tableWidgetFilmes.setColumnCount(0)
        self.tableWidgetFilmes.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetFilmes, 0, 0, 1, 3)
        self.pushButtonApagarFilmes = QtWidgets.QPushButton(self.frameConsultarFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonApagarFilmes.setFont(font)
        self.pushButtonApagarFilmes.setObjectName("pushButtonApagarFilmes")
        self.gridLayout.addWidget(self.pushButtonApagarFilmes, 1, 0, 1, 1)
        self.gridLayoutContent.addWidget(self.frameConsultarFilmes, 2, 1, 1, 1)
        self.frameInserirFilmes = QtWidgets.QFrame(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameInserirFilmes.sizePolicy().hasHeightForWidth())
        self.frameInserirFilmes.setSizePolicy(sizePolicy)
        self.frameInserirFilmes.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frameInserirFilmes.setFrameShape(QtWidgets.QFrame.Box)
        self.frameInserirFilmes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameInserirFilmes.setLineWidth(2)
        self.frameInserirFilmes.setObjectName("frameInserirFilmes")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameInserirFilmes)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonLimpar = QtWidgets.QPushButton(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonLimpar.setFont(font)
        self.pushButtonLimpar.setObjectName("pushButtonLimpar")
        self.gridLayout_2.addWidget(self.pushButtonLimpar, 14, 0, 1, 1)
        self.pushButtonInserir = QtWidgets.QPushButton(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonInserir.setFont(font)
        self.pushButtonInserir.setCheckable(False)
        self.pushButtonInserir.setObjectName("pushButtonInserir")
        self.gridLayout_2.addWidget(self.pushButtonInserir, 14, 1, 1, 1)
        self.lineEditRealizador = QtWidgets.QLineEdit(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditRealizador.setFont(font)
        self.lineEditRealizador.setObjectName("lineEditRealizador")
        self.gridLayout_2.addWidget(self.lineEditRealizador, 3, 1, 1, 1)
        self.lineEditNome = QtWidgets.QLineEdit(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditNome.setFont(font)
        self.lineEditNome.setObjectName("lineEditNome")
        self.gridLayout_2.addWidget(self.lineEditNome, 0, 1, 1, 1)
        self.labelPnome = QtWidgets.QLabel(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPnome.setFont(font)
        self.labelPnome.setObjectName("labelPnome")
        self.gridLayout_2.addWidget(self.labelPnome, 0, 0, 1, 1)
        self.labelIdade = QtWidgets.QLabel(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelIdade.setFont(font)
        self.labelIdade.setObjectName("labelIdade")
        self.gridLayout_2.addWidget(self.labelIdade, 4, 0, 1, 1)
        self.labelUnome = QtWidgets.QLabel(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelUnome.setFont(font)
        self.labelUnome.setObjectName("labelUnome")
        self.gridLayout_2.addWidget(self.labelUnome, 3, 0, 1, 1)
        self.labelProfissao = QtWidgets.QLabel(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelProfissao.setFont(font)
        self.labelProfissao.setObjectName("labelProfissao")
        self.gridLayout_2.addWidget(self.labelProfissao, 5, 0, 1, 1)
        self.spinBoxAno = QtWidgets.QSpinBox(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBoxAno.setFont(font)
        self.spinBoxAno.setMinimum(1888)
        self.spinBoxAno.setMaximum(2025)
        self.spinBoxAno.setProperty("value", 2022)
        self.spinBoxAno.setObjectName("spinBoxAno")
        self.gridLayout_2.addWidget(self.spinBoxAno, 4, 1, 1, 1)
        self.comboBoxGenero = QtWidgets.QComboBox(self.frameInserirFilmes)
        self.comboBoxGenero.setMaxCount(2147483633)
        self.comboBoxGenero.setMinimumContentsLength(2)
        self.comboBoxGenero.setProperty("Tipo", "Comédia\n"
"Ação")
        self.comboBoxGenero.setObjectName("comboBoxGenero")
        self.comboBoxGenero.addItem("")
        self.comboBoxGenero.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxGenero, 6, 1, 1, 1)
        self.labelProfissao_3 = QtWidgets.QLabel(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelProfissao_3.setFont(font)
        self.labelProfissao_3.setObjectName("labelProfissao_3")
        self.gridLayout_2.addWidget(self.labelProfissao_3, 6, 0, 1, 1)
        self.doubleSpinBoxClassificacao = QtWidgets.QDoubleSpinBox(self.frameInserirFilmes)
        self.doubleSpinBoxClassificacao.setDecimals(1)
        self.doubleSpinBoxClassificacao.setMaximum(10.0)
        self.doubleSpinBoxClassificacao.setSingleStep(0.1)
        self.doubleSpinBoxClassificacao.setProperty("value", 5.0)
        self.doubleSpinBoxClassificacao.setObjectName("doubleSpinBoxClassificacao")
        self.gridLayout_2.addWidget(self.doubleSpinBoxClassificacao, 5, 1, 1, 1)
        self.spinBoxSala = QtWidgets.QSpinBox(self.frameInserirFilmes)
        self.spinBoxSala.setMinimum(1)
        self.spinBoxSala.setMaximum(10)
        self.spinBoxSala.setObjectName("spinBoxSala")
        self.gridLayout_2.addWidget(self.spinBoxSala, 8, 1, 1, 1)
        self.labelProfissao_4 = QtWidgets.QLabel(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelProfissao_4.setFont(font)
        self.labelProfissao_4.setObjectName("labelProfissao_4")
        self.gridLayout_2.addWidget(self.labelProfissao_4, 8, 0, 1, 1)
        self.spinBoxReservas = QtWidgets.QSpinBox(self.frameInserirFilmes)
        self.spinBoxReservas.setMinimum(1)
        self.spinBoxReservas.setMaximum(10)
        self.spinBoxReservas.setObjectName("spinBoxReservas")
        self.gridLayout_2.addWidget(self.spinBoxReservas, 9, 1, 1, 1)
        self.labelProfissao_2 = QtWidgets.QLabel(self.frameInserirFilmes)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelProfissao_2.setFont(font)
        self.labelProfissao_2.setObjectName("labelProfissao_2")
        self.gridLayout_2.addWidget(self.labelProfissao_2, 9, 0, 1, 1)
        self.gridLayoutContent.addWidget(self.frameInserirFilmes, 2, 0, 1, 1)
        self.labelInserirFilmes = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInserirFilmes.sizePolicy().hasHeightForWidth())
        self.labelInserirFilmes.setSizePolicy(sizePolicy)
        self.labelInserirFilmes.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelInserirFilmes.setObjectName("labelInserirFilmes")
        self.gridLayoutContent.addWidget(self.labelInserirFilmes, 1, 0, 1, 1)
        self.labelTitulo = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelTitulo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitulo.sizePolicy().hasHeightForWidth())
        self.labelTitulo.setSizePolicy(sizePolicy)
        self.labelTitulo.setObjectName("labelTitulo")
        self.gridLayoutContent.addWidget(self.labelTitulo, 0, 1, 1, 1)
        self.frameInserirFilmes_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameInserirFilmes_2.sizePolicy().hasHeightForWidth())
        self.frameInserirFilmes_2.setSizePolicy(sizePolicy)
        self.frameInserirFilmes_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frameInserirFilmes_2.setAutoFillBackground(False)
        self.frameInserirFilmes_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frameInserirFilmes_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameInserirFilmes_2.setLineWidth(2)
        self.frameInserirFilmes_2.setObjectName("frameInserirFilmes_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameInserirFilmes_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonReservar = QtWidgets.QPushButton(self.frameInserirFilmes_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonReservar.setFont(font)
        self.pushButtonReservar.setObjectName("pushButtonReservar")
        self.gridLayout_3.addWidget(self.pushButtonReservar, 6, 2, 1, 1)
        self.labelPnome_2 = QtWidgets.QLabel(self.frameInserirFilmes_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPnome_2.setFont(font)
        self.labelPnome_2.setObjectName("labelPnome_2")
        self.gridLayout_3.addWidget(self.labelPnome_2, 2, 0, 1, 1)
        self.spinBoxBilhetes = QtWidgets.QSpinBox(self.frameInserirFilmes_2)
        self.spinBoxBilhetes.setMinimum(1)
        self.spinBoxBilhetes.setMaximum(10)
        self.spinBoxBilhetes.setObjectName("spinBoxBilhetes")
        self.gridLayout_3.addWidget(self.spinBoxBilhetes, 4, 2, 1, 1)
        self.comboBoxFilmes = QtWidgets.QComboBox(self.frameInserirFilmes_2)
        self.comboBoxFilmes.setObjectName("comboBoxFilmes")
        self.gridLayout_3.addWidget(self.comboBoxFilmes, 2, 1, 1, 2)
        self.labelProfissao_8 = QtWidgets.QLabel(self.frameInserirFilmes_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelProfissao_8.setFont(font)
        self.labelProfissao_8.setObjectName("labelProfissao_8")
        self.gridLayout_3.addWidget(self.labelProfissao_8, 4, 0, 1, 1)
        self.gridLayoutContent.addWidget(self.frameInserirFilmes_2, 2, 2, 1, 1)
        self.gridLayoutTitle.addLayout(self.gridLayoutContent, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 24))
        self.menubar.setObjectName("menubar")
        self.menuFicheiro = QtWidgets.QMenu(self.menubar)
        self.menuFicheiro.setObjectName("menuFicheiro")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/py/71029_as_guardar_save_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar.setIcon(icon)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_Como = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/py/23221_as_document_guardar_save_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar_Como.setIcon(icon1)
        self.actionGuardar_Como.setObjectName("actionGuardar_Como")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionFicheiro_CSV = QtWidgets.QAction(MainWindow)
        self.actionFicheiro_CSV.setObjectName("actionFicheiro_CSV")
        self.actionAbrir_2 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/py/416376_envelope_files_folder_interface_office_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir_2.setIcon(icon2)
        self.actionAbrir_2.setObjectName("actionAbrir_2")
        self.menuFicheiro.addAction(self.actionAbrir_2)
        self.menuFicheiro.addAction(self.actionGuardar)
        self.menuFicheiro.addAction(self.actionGuardar_Como)
        self.menuFicheiro.addSeparator()
        self.menuFicheiro.addAction(self.actionSair)
        self.menuAjuda.addAction(self.actionSobre)
        self.menubar.addAction(self.menuFicheiro.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBoxGenero.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonGrafico.setText(_translate("MainWindow", "Gráfico das reservas"))
        self.pushButtonAtualizarTabela.setText(_translate("MainWindow", "Atualizar"))
        self.pushButtonApagarFilmes.setText(_translate("MainWindow", "Apagar"))
        self.pushButtonLimpar.setText(_translate("MainWindow", "Limpar"))
        self.pushButtonInserir.setText(_translate("MainWindow", "Inserir"))
        self.labelPnome.setText(_translate("MainWindow", "Nome"))
        self.labelIdade.setText(_translate("MainWindow", "Ano"))
        self.labelUnome.setText(_translate("MainWindow", "Realizador"))
        self.labelProfissao.setText(_translate("MainWindow", "Classificação"))
        self.comboBoxGenero.setProperty("Type", _translate("MainWindow", "ação\n"
"comédia"))
        self.comboBoxGenero.setItemText(0, _translate("MainWindow", "Ação"))
        self.comboBoxGenero.setItemText(1, _translate("MainWindow", "Comédia"))
        self.labelProfissao_3.setText(_translate("MainWindow", "Genero"))
        self.labelProfissao_4.setText(_translate("MainWindow", "Sala"))
        self.labelProfissao_2.setText(_translate("MainWindow", "Reservas"))
        self.labelInserirFilmes.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Cadastrar Filmes</span></p></body></html>"))
        self.labelTitulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Aplicação Filmoteca</span><span style=\" font-weight:600;\"><br/></span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Inserir, Alterar e Apagar e Reservar filmes </span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Carregar ficheiros CSV, consultar, acrescentar e apagar</span></p></body></html>"))
        self.pushButtonReservar.setText(_translate("MainWindow", "Reservar"))
        self.labelPnome_2.setText(_translate("MainWindow", "Filme"))
        self.labelProfissao_8.setText(_translate("MainWindow", "Quantidade"))
        self.menuFicheiro.setTitle(_translate("MainWindow", "Ficheiro"))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionGuardar_Como.setText(_translate("MainWindow", "Guardar Como..."))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
        self.actionFicheiro_CSV.setText(_translate("MainWindow", "Ficheiro CSV"))
        self.actionAbrir_2.setText(_translate("MainWindow", "Abrir"))



        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButtonInserir.clicked.connect(self.inserirFilmes)  
        self.pushButtonLimpar.clicked.connect(self.limparCampos)
        self.pushButtonInserir.clicked.connect(self.inserirFilmes)
        self.actionGuardar_Como.triggered.connect(self.GuardarComo)
        self.actionAbrir_2.triggered.connect(self.AbrirCsv)
        self.pushButtonAtualizarTabela.clicked.connect(self.tabelaAlterada)
        self.pushButtonGrafico.clicked.connect(self.grafico)
        self.pushButtonReservar.clicked.connect(self.reservar)
        self.pushButtonAtualizarTabela.setDisabled(True)
        self.pushButtonApagarFilmes.setDisabled(True)
        self.pushButtonAtualizarTabela.setVisible(False)
        self.pushButtonApagarFilmes.setVisible(False)

    def showDialog(self):
            text, ok = QInputDialog.getText(self, 'Input Dialog', 'Enter text:')
            if ok:
                self.le.setText(str(text))

    def fillCombobox(self):
        self.comboBoxFilmes.clear()
        for i in afs.objFilmes:
            self.comboBoxFilmes.addItem(i.obterNome())
            

    def reservar(self):
        filmeIndex = self.comboBoxFilmes.currentIndex()
        numBilhetesAtual = afs.objFilmes[filmeIndex].obterReservas()
        print("Disponíveis: ", numBilhetesAtual)
        numBilhetesSelecionado = (int)(self.spinBoxBilhetes.value())
        print("Desejados: ", numBilhetesSelecionado)
        bilhetesRestantes = (int)(numBilhetesAtual) - (int)(numBilhetesSelecionado)
        print("Restantes: ",bilhetesRestantes)
        
        
        if(bilhetesRestantes < 0):
            msg = QMessageBox()
            msg.setText("Não há mais bilhetes disponíveis para este filme")
            msg.setWindowTitle("Atenção")
            msg.exec_()
        else:
            afs.objFilmes[filmeIndex].alterarReservas(bilhetesRestantes)
            print("Reservas atualizada: ",(afs.objFilmes[filmeIndex].obterReservas()))
            self.tableWidgetFilmes.setItem(filmeIndex,6,QtWidgets.QTableWidgetItem(str(afs.objFilmes[filmeIndex].obterReservas())))
            
        # self.window = QtWidgets.QDialog()
        # self.ui = Ui_Dialog()
        # self.setupUi = (self.window)
        # self.window.show
    
    def limparCampos(self):
        self.lineEditNome.setText('')
        self.lineEditRealizador.setText('')
        self.spinBoxAno.setValue(2022)
        self.doubleSpinBoxClassificacao.setValue(5.0)
        self.spinBoxSala.setValue(1)
        self.spinBoxReservas.setValue(1)

    def inserirFilmes(self):
        if self.lineEditNome.text() != '' and self.lineEditRealizador.text() != '' and self.spinBoxAno.value()> 0 and  \
            self.spinBoxReservas.value() > 0 and self.spinBoxReservas.value() > 0 and self.spinBoxSala.value() >0 and self.comboBoxGenero.currentText() != '':
            afs.objFilmes.append(afs.Filmes(self.lineEditNome.text(),self.lineEditRealizador.text(),self.spinBoxAno.value(),self.doubleSpinBoxClassificacao.value(), \
            self.comboBoxGenero.currentText(), self.spinBoxSala.value(),self.spinBoxReservas.value()))
        print(afs.objFilmes)
        self.updateTable()

    def buscarFilme(self):
        if self.lineEditNome.text() in afs.objFilmes:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Question) # Warning, Question, Information, Critical
                msg.setText("Foram feitas alterações.")
                msg.setInformativeText("Deseja Confirmar as reservas efetuadas?")
                msg.setWindowTitle("Pergunta")
                msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No) # Ok | Cancel / Yes | No | Cancel
                msg.exec_()

    def updateTable(self):
            self.tableWidgetFilmes.setRowCount(len(afs.objFilmes)) # Numero de linhas da tabela
            self.tableWidgetFilmes.setColumnCount(7) # Numero de colunas da tabela
            self.tableWidgetFilmes.setHorizontalHeaderLabels(['Nome','Realizador','Ano','Classificação','Género','Sala','Reservas'])
            
            print(len(afs.objFilmes))
            self.tableWidgetFilmes.setItem(len(afs.objFilmes) - 1,0,QtWidgets.QTableWidgetItem(afs.objFilmes[len(afs.objFilmes) - 1].obterNome()))
            self.tableWidgetFilmes.setItem(len(afs.objFilmes) - 1,1,QtWidgets.QTableWidgetItem(afs.objFilmes[len(afs.objFilmes) - 1].obterRealizador()))
            self.tableWidgetFilmes.setItem(len(afs.objFilmes) - 1,2,QtWidgets.QTableWidgetItem(str(afs.objFilmes[len(afs.objFilmes) - 1].obterAno())))
            self.tableWidgetFilmes.setItem(len(afs.objFilmes) - 1,3,QtWidgets.QTableWidgetItem(str(afs.objFilmes[len(afs.objFilmes) - 1].obterClassificacao())))
            self.tableWidgetFilmes.setItem(len(afs.objFilmes) - 1,4,QtWidgets.QTableWidgetItem(afs.objFilmes[len(afs.objFilmes) - 1].obterGenero()))
            self.tableWidgetFilmes.setItem(len(afs.objFilmes) - 1,5,QtWidgets.QTableWidgetItem(str(afs.objFilmes[len(afs.objFilmes) - 1].obterSala())))
            self.tableWidgetFilmes.setItem(len(afs.objFilmes) - 1,6,QtWidgets.QTableWidgetItem(str(afs.objFilmes[len(afs.objFilmes) - 1].obterReservas())))
            self.tableWidgetFilmes.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
            self.tableWidgetFilmes.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
            self.tableWidgetFilmes.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
            self.tableWidgetFilmes.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.Stretch)
            self.tableWidgetFilmes.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.Stretch)
            self.tableWidgetFilmes.horizontalHeader().setSectionResizeMode(5, QtWidgets.QHeaderView.Stretch)
            self.tableWidgetFilmes.horizontalHeader().setSectionResizeMode(6, QtWidgets.QHeaderView.Stretch)

            self.fillCombobox()
        
            self.limparCampos()
        
    def GuardarComo(self):
        nome = QFileDialog.getSaveFileName(None,'Guardar CSV','teste','*.csv')
        print(nome)
        if nome[0] != '':
            self.saveCSV(nome[0])


    def saveCSV(self,nome_ficheiro_save):
        file = open(nome_ficheiro_save,'w',encoding='utf-8',newline='')
        writer = csv.writer(file,delimiter=',')
        writer.writerow([nome,realizador,ano,classificacao, genero, sala, reservas])
        for i in afs.objFilmes:
            nome = i.obterNome()
            realizador = i.obterRealizador()
            ano = i.obterAno()
            classificacao = i.obterClassificacao()
            genero = i.obterGenero()
            sala = i.obterSala()
            reservas = i.obterReservas()
            writer.writerow([nome,realizador,ano,classificacao, genero, sala, reservas])
        
        file.close()

    def AbrirCsv(self):
        janelaAbrir = QFileDialog()
        janelaAbrir.setNameFilter("Ficheiros CSV (*.csv)")

        # Criar um QStringListModel() - Modelo para PyQt para abrir ficheiros via QFileDialog

        nome_ficheiro = QStringListModel()

        if janelaAbrir.exec_():
            nome_ficheiro = janelaAbrir.selectedFiles()
            print(nome_ficheiro)
            file = open(nome_ficheiro[0],'r',encoding='utf=8')
            csv_reader = csv.reader(file)
            next(csv_reader) #não importar Header TM
            for row in csv_reader:
                afs.objFilmes.append(afs.Filmes(row[0],row[1],row[2],\
                row[3],row[4],row[5],row[6]))
                self.updateTable()

    def tabelaAlterada(self):
        flag_change = False
        for i in range(len(afs.objFilmes)):
            if afs.objFilmes[i].obterNome() != self.tableWidgetFilmes.item(i,0).text() or \
                afs.objFilmes[i].obterRealizador() != self.tableWidgetFilmes.item(i,1).text() or \
                str(afs.objFilmes[i].obterAno()) != self.tableWidgetFilmes.item(i,2).text() or \
                str(afs.objFilmes[i].obterClassificacao()) != self.tableWidgetFilmes.item(i,3).text() or \
                str(afs.objFilmes[i].obterGenero()) != self.tableWidgetFilmes.item(i,4).text() or \
                str(afs.objFilmes[i].obterSala()) != self.tableWidgetFilmes.item(i,5).text() or \
                str(afs.objFilmes[i].obterReservas()) != self.tableWidgetFilmes.item(i,6).text():
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Question) # Warning, Question, Information, Critical
                msg.setText("Foram feitas alterações.")
                msg.setInformativeText("Deseja Confirmar as reservas efetuadas?")
                msg.setWindowTitle("Pergunta")
                msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No) # Ok | Cancel / Yes | No | Cancel
                msg.exec_()
                if msg.standardButton(msg.clickedButton()) == QMessageBox.Yes:
                    flag_change = True
                    break
                else:
                    self.updateTable()
        if flag_change == True:
            afs.objFilmes.clear()
            for i in range(self.tableWidgetFilmes.rowCount()):
                afs.objFilmes.append(afs.Filmes(self.tableWidgetFilmes.item(i,0).text(), \
                    self.tableWidgetFilmes.item(i,1).text(),\
                    self.tableWidgetFilmes.item(i,2).text(),\
                    self.tableWidgetFilmes.item(i,3).text(),\
                    self.tableWidgetFilmes.item(i,4).text(),\
                    self.tableWidgetFilmes.item(i,5).text(),\
                    self.tableWidgetFilmes.item(i,6).text()))

    #Estudos para Matplotlib



    def grafico(self):
        afs.df[["Reservas"]].plot()
        plt.show
        

    # def grafico(self):
    #     objects = (1,2,3,4,5,6)
    #     y_pos = np.arange(len(objects))
    #     performance = [10,8,6,4,2,1]
    #     plt.bar(y_pos, performance, align='center', alpha=0.5)
    #     plt.xticks(y_pos, objects)
    #     plt.ylabel('Reservas')
    #     plt.title('Reservas efetuadas')
    #     plt.show()

    def grafico(self):
        nomeGrafico = []
        reservaGrafico = []
        for i in afs.objFilmes:
            nomeGrafico.append(i.obterNome())
            reservaGrafico.append(int(i.obterReservas()))
    
    
        # ordene os índices em vez dos elementos em si
        indices = list(range(len(reservaGrafico)))
        indices.sort(key=lambda i: reservaGrafico[i]) # ordene os índices com relação ao seu respectivo valor em x

        # crie as listas baseado na ordem dos índices
        newReservaGrafico = [reservaGrafico[i] for i in indices]
        newNomeGrafico = [nomeGrafico[i] for i in indices]

    
        y_pos = np.arange(len(newNomeGrafico))
        plt.bar(y_pos, newReservaGrafico, align='center', alpha=0.5)
        plt.xticks(y_pos, newNomeGrafico)
        plt.ylabel('Reservas')
        plt.title('Reservas efetuadas')
        plt.show()
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    import aplicacaoFilmesClasse as afs
    import csv
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
